Dont show notice if modules are active in free version
Strategy11/business-directory-plugin pull request #114
Opened 2022-01-18 07:32 UTC by theRealRizeo

This disables the notice when one of the BD modules is activated with a valid license.
Before:

![image](https://user-images.githubusercontent.com/121492/149890545-a4fcff38-5720-4447-824d-dcb4a7a4381d.png)

After:

![image](https://user-images.githubusercontent.com/121492/149890907-b91918fd-54fa-436f-bbaa-a3c23e6e446f.png)
![image](https://user-images.githubusercontent.com/121492/149890934-889364fe-b031-408e-b1d0-ea64533e2126.png)

2022-01-18 16:01 UTC, stephywells requested changes
Thanks @theRealRizeo ! This is a nice a clean fix.

2022-01-18 16:01 UTC, stephywells commented on includes/admin/class-admin.php
> +			if ( $modules->is_loaded( 'premium' ) || count( array_keys( $modules->get_modules() ) ) > 0 ) {
Can we exclude the Enhanced Categories module from this check? A lot of people have gotten it free.

2022-01-19 04:29 UTC, garretlaxton approved these changes
Looks good!

2022-01-19 19:24 UTC, stephywells approved these changes
Nice job on this @theRealRizeo !

2022-01-19 19:24 UTC, merged