Edit Listing Fee Plan Error Message
Strategy11/business-directory-plugin pull request #133
Opened 2022-02-14 10:14 UTC by theRealRizeo

Reported issue : https://github.com/Strategy11/BusinessDirectoryPlugin/issues/5033

This is a special case that should happen in a very rare occasion. Steps to reproduce

- Create a listing that has a premium plan assigned to it and publish it
- Edit the Fee plans and disable all plans and gateways
- Proceed to edit listing and an error message will show. Previous message was : `"Please choose a valid category for your plan."` . New message is : `"Current active fee plan is disabled. Please select another fee plan."` (may need better wording)

A better option would be to show a message on load or disable the "Next" button for a listing that fits the above criteria

![image](https://user-images.githubusercontent.com/121492/153844549-88ff6443-a9a8-4e99-aa7c-047b22dc22a3.png)

![image](https://user-images.githubusercontent.com/121492/153844570-6a4546b2-521e-40a5-8e17-7a109cefdcb9.png)

2022-02-14 20:25 UTC, garretlaxton approved these changes
Looks good, but is says select another plan which you can't do when editing the listing.
![Screenshot 2022-02-14 at 15-23-40 BD QA – Just another WordPress site](https://user-images.githubusercontent.com/16290508/153940769-fd632286-091b-4563-9a02-d200b72fde3c.png)

2022-02-15 07:30 UTC, theRealRizeo commented
Yes, we may need to either disable the "Next" button when there are no enabled plans, which I think would be a good option for this

2022-02-15 16:16 UTC, stephywells commented
So it sounds like we need a different message when there are no plans to choose from. Was this an error with the migration that disabled a plan that shouldn't have been disabled?

Before a plan is disabled, can we check if there are other plans enabled? If not, we should show a message and don't disable the plan.

2022-02-15 18:02 UTC, theRealRizeo commented
@stephywells before the PR to remove the payments settings, the default fee plan could not be enabled or disabled, but would show on certain conditions. If payments were turned on, the default plan would not be shown and vice versa. 

> Before a plan is disabled, can we check if there are other plans enabled? If not, we should show a message and don't disable the plan.

Will work on this :)

2022-02-15 20:11 UTC, stephywells commented
But is it possible the migration disabled this plan on their site?

2022-02-15 22:49 UTC, garretlaxton commented
@stephywells Not sure what you are referring to by migration, but it was the 5.17 update I'm pretty sure. A bug in 5.17 disabled free plans when we removed the _turn payments on_ option.

2022-02-16 08:18 UTC, theRealRizeo commented
@stephywells before the default free plan would not be allowed to be disabled or enabled. When we allowed this option in this PR https://github.com/Strategy11/business-directory-plugin/pull/126 then is allowed for there to be a state of no plan active. Before the default plan would disable if there are payment gateways enabled and vice versa. 
Allowing the admin to enable/disable the default free plan would bring about this.

The migration did not affect as it only checked for the payment option, this scenario can be replicated on a fresh install by manually disabling all plans and trying to edit an existing listing that has a plan. Suggested options :

- We add a check before disabling a plan to alert the admin this will affect listings that will be edited
- Before all plans are disabled, we show a notice to the admin that they are about to disable creating a new listing in the frontend

2022-02-17 03:46 UTC, stephywells requested changes
Nice job! just a couple wording and code types of requests.

2022-02-17 03:46 UTC, stephywells commented on includes/controllers/pages/class-submit-listing.php
> +						$this->messages( _x( 'Current active fee plan is disabled. Please select another fee plan.', 'submit listing', 'business-directory-plugin' ), 'error', 'plan_selection' );
Let's use "plan" going forward instead of "fee plan". It's confusing since they don't have to have a fee.

2022-02-17 03:46 UTC, stephywells commented on includes/class-fees-api.php
> +	public static function has_enabled_plans() {
Can we reduce duplication here a bit by adding has_enabled_plans( $paid = null )

Then:
$cache_key = 'enabled_plan_count';
$query = "SELECT count(*) FROM {$wpdb->prefix}wpbdp_plans WHERE enabled != 0";
if ( $paid ) {
$cache_key = 'paid_plan_count';
$query .= "AND amount > 0";
}

2022-02-17 03:46 UTC, stephywells commented on includes/admin/controllers/class-admin-fees.php
> +			wpbdp_admin_message( $fee->enabled ? _x( 'Fee enabled.', 'fees admin', 'business-directory-plugin' ) : _x( 'Fee disabled.', 'fees admin', 'business-directory-plugin' ) );
Let's use "plan" here too instead of "fee"

2022-02-17 15:47 UTC, stephywells approved these changes
Nice! This looks great!

2022-02-17 15:48 UTC, merged