Make the prompt to upgrade dismissible
Strategy11/business-directory-plugin pull request #273
Opened 2022-11-17 00:13 UTC by shervElmi

### Issue link:
https://github.com/Strategy11/business-directory-premium/issues/103

### Changes proposed in this PR:
With this PR, we will make the Download Premium notice dismissible.

### How to test the changes in this Pull Request:
- Active one BD add-on without activating the Premium version.
- You need to dismiss the `"You have modules installed, but Business Directory Premium is missing. Install this plugin for extra features and easy license management."` notice in the BD admin panel and another page in wp-admin, like the Plugins page management.
- In both cases, this message should not be displayed after dismissing you.

2022-11-17 16:31 UTC, garretlaxton approved these changes
This looks good! It now stays dismissed after you click.

2022-11-17 20:46 UTC, stephywells requested changes
Nice fix! I just have one small request for the admin-wide js.

Once that is updated, will you go ahead and start on this checklist? https://app.asana.com/0/1189101947561289/1203292211866604/f

It's super important to have the release version PR merged before creating a release in Github. The Github release pushes to WP.org immediately, and if the version number is wrong, people will get infinite loops of update requests.

2022-11-18 11:57 UTC, shervElmi commented on assets/js/wp-admin.js
> +	var dismissNotice = function ( $notice ) {
The whole code is wrapped with invoked function! that means It prevents any conflict! but It's always suitable to prefix JavaScript functions to move them anywhere without worries. Thanks for your suggestion!

2022-11-18 11:59 UTC, shervElmi commented
> Nice fix! I just have one small request for the admin-wide js.
> 
> Once that is updated, will you go ahead and start on this checklist? https://app.asana.com/0/1189101947561289/1203292211866604/f
> 
> It's super important to have the release version PR merged before creating a release in Github. The Github release pushes to WP.org immediately, and if the version number is wrong, people will get infinite loops of update requests.

Thanks!
I'll check it with you to make sure I'm doing it right.

2022-11-18 12:07 UTC, stephywells approved these changes

2022-11-18 12:07 UTC, stephywells commented on assets/js/wp-admin.js
> +	var dismissNotice = function ( $notice ) {
Sounds good. You can go ahead and merge this PR then. Thanks!

2022-11-18 12:26 UTC, merged

2022-11-18 13:06 UTC, shervElmi commented
@stephywells 

Would you please explain to me what I should do to fix this:
https://github.com/Strategy11/business-directory-plugin/actions/runs/3496885594/jobs/5855319519

Thanks!

2022-11-18 16:05 UTC, stephywells commented
@shervElmi that doesn't require a fix. When only the readme is updated, that will push it to the wp.org repo immediately. But most of the time that won't be the case. The official releases are triggered when a new release is created here:
https://github.com/Strategy11/business-directory-plugin/releases