New Design - Search Components
Strategy11/business-directory-plugin pull request #292
Opened 2023-02-14 19:30 UTC by shervElmi

With this PR, we will implement the search bar and advanced search designs.

### Figma link:
https://www.figma.com/file/FelBhqZM5MVx7P3S4qikmr/Themes?node-id=1%3A2989&t=tROxcTXcpw5svkJp-4
https://www.figma.com/file/FelBhqZM5MVx7P3S4qikmr/Themes?node-id=1%3A2000&t=tROxcTXcpw5svkJp-4

2023-04-13 20:25 UTC, shervElmi commented
@stephywells, I encountered a PHPStan error in `includes/admin/helpers/csv/class-csv-import.php`. Should we address this issue or configure PHPStan to ignore it? Please advise on the preferred approach.

2023-04-13 22:07 UTC, stephywells commented
> @stephywells, I encountered a PHPStan error in `includes/admin/helpers/csv/class-csv-import.php`. Should we address this issue or configure PHPStan to ignore it? Please advise on the preferred approach.

I'm not seeing this file in the current Pr. Would you mind creating a new PR for that to fix the error? We can merge that into master to solve the problem.

2023-04-13 23:41 UTC, shervElmi commented
> > @stephywells, I encountered a PHPStan error in `includes/admin/helpers/csv/class-csv-import.php`. Should we address this issue or configure PHPStan to ignore it? Please advise on the preferred approach.
> 
> I'm not seeing this file in the current Pr. Would you mind creating a new PR for that to fix the error? We can merge that into master to solve the problem.

I have now created a new PR specifically to address this issue.

PR URL: https://github.com/Strategy11/business-directory-plugin/pull/301

2023-08-11 00:25 UTC, stephywells requested changes
I just started into this, but I think there will still be a lot of issues. Can you please send this PR through our regular review process? We'll need to compare before and after for every front-end facing page.
- select a plan
- submit a listing
- upload an image/file to a list
- see the confirmation page
- single listing
- list all
- advanced search
- (there might be more I'm not thinking of)

Thanks for the review and updates @mostafa-hisham !

2023-08-11 00:25 UTC, stephywells commented on assets/css/less/front-end/elements/buttons.less
> +		padding: 19px 40px;
This is causing some issues from me in Astra. The button is taller than the inputs. 0 top and bottom padding solves it for me. 
Before:
<img width="1250" alt="Screenshot 2023-08-10 at 5 57 00 PM" src="https://github.com/Strategy11/business-directory-plugin/assets/1116876/1edd5537-7e4f-4344-984b-cae0ca14bf61">

After:
<img width="1255" alt="Screenshot 2023-08-10 at 5 57 16 PM" src="https://github.com/Strategy11/business-directory-plugin/assets/1116876/0140eab1-0533-4b86-b18b-eda741fce128">

2023-08-11 00:25 UTC, stephywells commented on assets/css/less/front-end/elements/buttons.less
> +		border-radius: 4px;
Let's remove this line. I think we should let the theme handle the border radius so the buttons will match as closely as possible.

Without this line, here's what I see in Divi. The secondary button has the .et_pb_button class, but the main button doesn't have a class from the theme. Perhaps we need to apply the button class to the input submit too?
<img width="231" alt="Screenshot 2023-08-10 at 6 06 42 PM" src="https://github.com/Strategy11/business-directory-plugin/assets/1116876/835f6490-aa86-49fd-97e1-e56b1b10890a">

2023-08-11 00:25 UTC, stephywells commented on assets/css/less/front-end/components/submit-listing/plan-selection-section.less
> +		display: none;
I'm not sure why this is hidden. Here's what I saw before:
<img width="1234" alt="Screenshot 2023-08-10 at 6 18 44 PM" src="https://github.com/Strategy11/business-directory-plugin/assets/1116876/4007c1a7-8026-4412-afca-ec2aa30629e1">

But now nothing happens when I click, with no indication as to why it's not working.

2023-08-15 01:28 UTC, garretlaxton commented
When I make a search using the advanced search in mobile view, the Find Listing button doesn't have it's width.
Before search:
![image](https://github.com/Strategy11/business-directory-plugin/assets/16290508/f5862ca0-1e83-435e-a777-2fc189d35319)


After search:
![image](https://github.com/Strategy11/business-directory-plugin/assets/16290508/9e0b1e89-9f99-4fd1-8eae-057810cd93e8)

2023-08-15 16:55 UTC, garretlaxton commented
I'm still not seeing the width with the latest changes.

2023-08-15 22:54 UTC, garretlaxton commented
Hmmm, that's weird. I did clear my cache and also tested with an incognito window and still don't see it.

2023-08-16 16:48 UTC, garretlaxton approved these changes
I uploaded this to a different site and managed to see the changes. Not sure why I wasn't seeing it locally, but this looks good!
![image](https://github.com/Strategy11/business-directory-plugin/assets/16290508/a5e8066b-0903-4c22-9b91-6ee64aa75aa2)

2023-09-08 22:57 UTC, stephywells requested changes
Oops! I started a review and didn't submit it.

2023-09-08 22:58 UTC, stephywells commented on assets/css/less/submit-listing.less
>              margin: 15px;
I already fixed this.

2024-01-17 22:05 UTC, stephywells commented on includes/controllers/pages/class-search.php
> +		if ( $wpbdp_ajax_search_modal ) {
This is fixed.

2024-01-17 23:41 UTC, stephywells commented on assets/css/less/front-end/components/submit-listing/rootline.less
> +			&.wpbdp-submit-section-current {
Fixed

2024-01-18 01:01 UTC, stephywells commented on assets/css/less/front-end/elements/forms.less
> +		background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='14' height='8' fill='none' viewBox='0 0 14 8'%3E%3Cpath stroke='%23000' stroke-linecap='round' stroke-line
done.

2024-01-18 23:49 UTC, stephywells commented on assets/css/less/front-end/elements/buttons.less
> +		border-radius: 4px;
Done

2024-01-19 20:01 UTC, stephywells commented
@garretlaxton I would love it if you could look over this again. Here are the things we need to double check the appearance with multiple themes:
- All BD buttons
- Quick search
- Advanced search
- Select a plan
- Create a listing
- Upload an image in the listing
- Listing confirmation page

I think that should cover it.

2024-01-24 01:07 UTC, garretlaxton commented
The renew listing and edit buttons on the manage listings page doesn't have any space between the 2. I see this on every theme I tested.
![image](https://github.com/Strategy11/business-directory-plugin/assets/16290508/c91b5284-6ead-47ef-9f01-a3a003bc4414)

I think the X in the top right of the advanced search popup should be i little higher, it overlays the fields a little bit.
![image](https://github.com/Strategy11/business-directory-plugin/assets/16290508/91281f0c-aec9-459a-b6b8-619761317fb2)

2024-01-25 23:43 UTC, stephywells commented
Thanks for the finds! @garretlaxton can you tell me what theme (BD and WP) you were running for these screenshots?

2024-01-26 00:38 UTC, stephywells commented
I saw the issue with the space between the edit/delete buttons and fixed that. I found a few more styling issues with buttons and spacing on the checkout page and delete listing page.

I've got a possible fix incoming for the modal X and I think I'm seeing the multiselect issue too. So no need on the theme names for right now.

2024-01-30 19:15 UTC, stephywells approved these changes

2024-01-30 19:15 UTC, merged

2024-01-30 19:24 UTC, shervElmi commented
Yay! Thanks for your hard work on this, @stephywells! I'm so happy this PR is finally merged! You are awesome as always! 🚀 🪨

2024-02-01 16:14 UTC, stephywells commented
Thank you for all your help with this too @shervElmi !