fix category checkbox and multi select validation
Strategy11/business-directory-plugin pull request #327
Opened 2023-06-21 15:49 UTC by mostafa-hisham

fix #[162](https://github.com/Strategy11/business-directory-premium/issues/162)

2023-06-23 20:35 UTC, garretlaxton approved these changes
This looks great!

2023-07-06 19:12 UTC, stephywells requested changes

2023-07-06 19:12 UTC, stephywells commented on includes/controllers/pages/class-submit-listing.php
> +		$should_validate = ! empty( $_POST ) && ! empty( $_POST ['current_section'] ) && $_POST ['current_section'] === 'plan_selection';
Let's use the same function we used in other PRs to get the sanitized POST value.

2023-07-07 16:11 UTC, stephywells approved these changes
This looks perfect now. Thanks so much for those updates!

2023-07-10 18:36 UTC, merged