fix upload image after delete
Strategy11/business-directory-plugin pull request #328
Opened 2023-06-22 16:43 UTC by mostafa-hisham

fix #[160](https://github.com/Strategy11/business-directory-premium/issues/160)

2023-06-26 06:02 UTC, mostafa-hisham commented
@garretlaxton could you please take another look at it? I fixed the issue

2023-06-26 22:32 UTC, garretlaxton approved these changes
Nice, this looks great now!

2023-06-29 13:55 UTC, stephywells requested changes
This works great! Let's fix the codestyling here too, and then we can marge it.

2023-06-29 13:55 UTC, stephywells commented on assets/js/wpbdp.js
> +							if(t._slotsRemaining < t._slots){
Let's update this line to match the codestyling in other lines. It should be:
`if ( t._slotsRemaining < t._slots ) {`

2023-07-05 23:04 UTC, stephywells approved these changes
Perfect!

2023-07-06 07:10 UTC, merged