convert Null values of is_sticky to 0 to avoid sort problems
Strategy11/business-directory-plugin pull request #335
Opened 2023-08-07 17:38 UTC by mostafa-hisham

should help fixes #[33](https://github.com/Strategy11/business-directory-ratings/issues/33) when there is sticky listing

2023-08-08 21:15 UTC, garretlaxton approved these changes
This looks good as well!

2023-08-29 18:26 UTC, stephywells approved these changes
Looks good!

Just curious @mostafa-hisham . Have you checked the query speed to see if this affects it?

2023-09-05 21:05 UTC, stephywells commented
@mostafa-hisham Thanks for checking! Is there a better way of doing this that won't add extra load on the DB? What happens if we run the SELECT sticky query separately?

2023-09-06 19:48 UTC, stephywells commented
@mostafa-hisham I was thinking something like:
`$sticky_posts = "SELECT listing_id FROM {$wpdb->prefix}wpbdp_listings WHERE is_sticky=1";`

And then in the main query, we would add this to the WHERE query:
```
if ( $sticky_posts ) {
   ' AND in (' . implode( $sticky_posts, ',' ) . ')';
}
```

I think this might cut down the time, but I'm not positive.

2023-09-08 01:04 UTC, stephywells commented
Oh, right. But I think the same logic would apply, but using the ids for sorting. Right?

2023-09-08 20:37 UTC, stephywells requested changes
Thanks for trying that! I haven't tested it, but the code looks good, and that's great that it speeds it up a bit.

2023-09-08 20:37 UTC, stephywells commented on includes/class-query-integration.php
> +			$sticky_ids_str = '';
Can we reverse the logic here, so we only run the DB query when we use it?

2023-09-08 20:37 UTC, stephywells commented on includes/class-query-integration.php
> +		$results = $wpdb->get_results( "SELECT listing_id FROM {$wpdb->prefix}wpbdp_listings  WHERE is_sticky=1" );
Let's run the query through our check_cache() functions too.

2023-09-14 19:19 UTC, stephywells commented on includes/class-query-integration.php
> +		$results = $wpdb->get_results( "SELECT listing_id FROM {$wpdb->prefix}wpbdp_listings  WHERE is_sticky=1" );
Thanks for the update!

The group here should be for the table getting searched. This helps us keep track of when the cache should be cleared.

`'group' => 'wpbdp_listings',`

2023-09-14 19:20 UTC, stephywells requested changes
Just left one more comment. This could use a final round of testing too since we made some updates.

2023-09-15 18:00 UTC, stephywells commented on includes/class-query-integration.php
> +		$results = $wpdb->get_results( "SELECT listing_id FROM {$wpdb->prefix}wpbdp_listings  WHERE is_sticky=1" );
I made this change and merged in my changes from the other pr.

2023-09-15 18:01 UTC, stephywells approved these changes

2023-09-15 18:01 UTC, merged